import { DOCUMENTS_V1_3, SELLER_V1_3 } from './v1-3'
import { DELIVERY_TERMS } from '@/lib/delivery-policy'

// Keep earlier versions immutable. This publication does not activate orders,
// payment, scheduled erasure or changes to live database access.
export const SELLER_V1_4 = SELLER_V1_3
export const DOCUMENTS_V1_4 = structuredClone(DOCUMENTS_V1_3)
const email = SELLER_V1_4.email
const custom = 'Bütün NRS kıyafetleri müşterinin ürün bazında verdiği beden ölçülerine göre dikilir. Tüketicinin isteği veya kişisel ihtiyaçları doğrultusunda hazırlanan mallarda Mesafeli Sözleşmeler Yönetmeliğinin 15/1-b maddesindeki cayma hakkı istisnası, gerçek kişiselleştirme koşulları oluştuğunda uygulanır. Sadece standart beden seçilmesi tek başına yeterli değildir. Bu özellik sipariş öncesinde açıklanır. İstisna; ayıplı mal, hatalı üretim, yanlış gönderim, teslim etmeme veya diğer emredici tüketici haklarını ortadan kaldırmaz.'
const returns = `İade/değişim başvurunuzu sipariş numarası veya işlemi bulmaya yeterli bilgilerle ${email} adresine iletin. Kanunen geçerli diğer bildirim yöntemleri saklıdır; cayma hakkının kullanılması satıcının onayına bağlanmaz. İade taşıyıcısı henüz belirlenmemiştir. Yasal iade hakkınız varsa, ürünü güvenli biçimde paketleyerek seçtiğiniz uygun taşıyıcıyla geri gönderebilirsiniz. E-posta üzerinden gönderim adresi ve masrafın NRS tarafından karşılanma yöntemini isteyebilirsiniz. Ayrı bir iade adresi bildirilmemişse bu sayfadaki şirket adresi kullanılabilir. Yanıt beklemek yasal bildirim veya gönderim sürelerinizi uzatmaz; önceden onay ya da belirli bir taşıyıcıyla gönderim zorunlu değildir. NRS'nin düzenlediği masrafsız yöntem henüz yoksa, yaptığınız makul ve belgeli iade gönderim giderini NRS karşılar; ödeme yapmak zorunda kaldıysanız gönderim belgesini aynı e-postaya iletin. Ön bilgilendirmede taşıyıcı belirtilmediği için tüketiciye iade masrafı yüklenmez. Ücretsiz ilk teslimat, bu iade masrafı sorumluluğunu ortadan kaldırmaz. Anlaşmalı kargo, kapıdan alım veya takip hizmeti bulunduğu taahhüt edilmez.`
const retention = [
  `Bu bölüm veri kategorilerine göre saklama ve silme planını açıklar. Süre hedefleri otomatik silme yapıldığı anlamına gelmez. Şirketin veri envanteri, sorumlu kişi, fiili erişimler, yedekler ve hizmet sağlayıcı sözleşmeleriyle uygulama tamamlanmalıdır. İşleme şartı daha önce ortadan kalkmışsa gereksiz veri hedef süre sonuna kadar sırf bu plan nedeniyle tutulmaz.`,
  `Sipariş ve sözleşme: ürün, bedel, teslimat, kabul zamanı ve belge sürümü gibi ticari işlem için gerekli kayıtlar, uygulanabilir ticari belge saklama ve hakların korunması yükümlülükleriyle sınırlı saklanır. TTK 82 kapsamındaki ticari belgeler için ilgili takvim yılının bitiminden itibaren 10 yıllık süre esas alınır. Bu süre her profil alanına, her mesaja veya tüm beden ölçülerine topluca uygulanmaz.`,
  `Fatura ve muhasebe: kanunen gerekli fatura/defter alanları VUK 253 uyarınca ilgili yılı takip eden takvim yılından başlayarak 5 yıl; aynı belge TTK 82 kapsamında ise 10 yıl saklanır. Somut belge kapsamı ve varsa daha uzun özel yükümlülük muhasebe/hukuk değerlendirmesiyle belirlenir. Faturaya gereksiz beden ölçüsü eklenmez.`,
  `İletişim ve destek: siparişle ilişkili ticari yazışmalar ilgili belge ve uyuşmazlık sürelerine göre değerlendirilir. Siparişe dönüşmemiş genel sorular için talebin kapanmasından itibaren en geç 1 yıl içinde gereklilik ve silme incelemesi planlanır; amaç daha erken sona ermişse işlem daha erken yapılmalıdır. Pazarlama için yeniden kullanılmaz. Hesap/profil ve favoriler hizmet süresince, kapatma sonrasında ise yalnız kalan geçerli hukuki sebepler ölçüsünde tutulur.`,
  `Beden ölçüleri: üretimde kullanılan ayrı çalışma kopyaları için hedef, teslimattan sonra en geç 6 ay içinde silme/anonimleştirme gerekliliğini değerlendirmek ve hukuki dayanak kalmamış kayıtları ilgili imha süresi içinde kaldırmaktır. Bu süre kanuni bir ölçü saklama zorunluluğu veya altı ayda bütün kopyaların kesin silindiği garantisi değildir. Açık bir düzeltme, şikayet veya uyuşmazlık varsa yalnız gerekli ölçüler, belgelenmiş hukuki sebep ve süreyle, sınırlı erişimle muhafaza edilir; gerekçe sona erince tekrar değerlendirilir.`,
  `Sipariş/sözleşme özetindeki ölçü kopyası ayrıca ele alınmalıdır: hazırlanmış yerel sipariş altyapısı ölçüleri değiştirilemez belge özetine de koymaktadır. Bu yayın o altyapıyı veya bir silme işlemini açmaz. Ticari belge saklama yükümlülüğü bütün ölçülerin aynı süre tutulmasına kendiliğinden gerekçe değildir. Ölçüleri ayırma, erişimden çıkarma ve gerekiyorsa hukuka uygun arşiv/imha yöntemi, belge bütünlüğü ve ispat yükümlülükleriyle birlikte doğrulanmadan tüm ölçülerin altı ayda silindiği söylenemez.`,
  `Silme ve yedekler: şirkette bu planı yerine getirecek yetkili belirlenmeli; e-posta/WhatsApp, üretim notları, tarayıcı kayıtları, Supabase kayıtları, dışa aktarımlar ve manuel yedekler dahil kopyalar değerlendirilmelidir. Başvuru üzerine kanuni şartlar varsa işlem yapılır; tutulması gereken sınırlı kayıt ve hukuki sebebi açıklanır. Silme/yok etme/anonimleştirme işlem kayıtları en az 3 yıl tutulur. Yedek dönüşlerinde silinmiş verinin yeniden olağan kullanıma alınmasını önleyen yöntem ayrıca hazırlanmalıdır.`,
  `Mevcut yayında otomatik silme zamanlayıcısı yoktur. İmha yükümlülüğü buna rağmen devam eder. Saklama/imha politikası hazırlama yükümlülüğü varsa periyodik imha aralığı en fazla 6 ay; bu yükümlülük yoksa işleme şartları sona erdiğinde imha için yönetmelikteki en fazla 3 aylık süre uygulanır. Bu aralıklar beden ölçülerine ilişkin 6 aylık hedefle aynı şey değildir. İlgili kişi başvuruları en geç 30 gün içinde cevaplandırılır.`,
]
const providers = [
  `Alıcı grupları, ihtiyaca göre teknik altyapı/veritabanı ve barındırma sağlayıcıları, teslimatı fiilen üstlenen taşıyıcı, şirketin yetkili üretim/destek personeli, gerekli muhasebe/hukuk hizmeti sağlayıcıları ve kanunen yetkili kurumlarla sınırlıdır. Taşıyıcıya teslimat için gereken ad, adres ve iletişim verileri iletilir; beden ölçüleri kargo işlemi için gerekli değildir. Meta'ya ölçü veya sipariş ayrıntısı gönderilmez. WhatsApp/e-posta tercih edildiğinde mesaj içeriği ilgili iletişim hizmeti sağlayıcısında da işlenir.`,
  `Supabase hesap/müşteri veritabanı hizmeti için kullanılır; kayıtlı sipariş ve ölçü altyapısı ayrıca doğrulanıp açıldığında bu kayıtlar da burada işlenir. Vercel siteyi barındırır; isteklerin iletimi, sunucu çalışması ve altyapı kayıtları kapsamında gerekli verileri işleyebilir. Meta Pixel reklam/sayfa görüntüleme ölçümü içindir ve ayrı isteğe bağlı izinle yüklenir. Garanti BBVA planlanan ödeme sağlayıcısıdır; bu yayında kart ödeme kapalıdır ve NRS tarafından bu entegrasyon üzerinden bankaya ödeme verisi gönderilmez. Gelecekteki ödeme veri alanları ve saklama koşulları gerçek yöntem doğrulandığında açıklanmalıdır.`,
  `Hesap ve sipariş için gerekli veriler sözleşmenin kurulması/ifası; kanuni kayıtlar yasal yükümlülük; uyuşmazlık delilleri hakkın tesisi, kullanılması veya korunması amaçlarıyla sınırlı işlenir. NRS kodundaki reklam izni sözleşme onayından ayrıdır. Gerekli teknik altyapı ve güvenlik kayıtları için kapsamına uygun hukuki sebep ayrıca değerlendirilir; bütün işlemler için genel açık rıza varsayılmaz.`,
  `Supabase proje bölgesi, Vercel çalışma/log bölgeleri, alt işleyenler, destek erişimleri ve Meta/WhatsApp veri akışları nedeniyle yurt dışına aktarım gündeme gelebilir. Bu yayında gerçek hesap bölgeleri, sağlayıcı saklama süreleri ve imzalı aktarım belgeleri doğrulanmamıştır; verilerin yalnız Türkiye'de veya seçilen tek bölgede kaldığı söylenmez. İlgili veri işleme sözleşmeleri ve KVKK 9 kapsamındaki uygun aktarım dayanağı veri akışı bazında tamamlanmalıdır. Yabancı sağlayıcının genel DPA belgesi veya reklam izni tek başına bu işlemlerin tamamlandığı anlamına gelmez.`,
  `Uygun yöntem yeterlilik kararı, uygun güvence veya kanundaki diğer şartlara göre değerlendirilir. Standart sözleşme yöntemi seçilirse Kurumun ilgili metni, doğru taraflar/ekler ve imzalarla düzenlenmeli, imzadan itibaren 5 iş günü içinde Kuruma bildirilmelidir. Düzenli bulut hizmeti aktarımı için arızi aktarım istisnası otomatik varsayılmaz. Aktarım dayanağı ve fiili uygulama hukuk incelemesiyle doğrulanmadan tamamlanmış uyum iddiasında bulunulmaz.`,
]
const measurements = [
  `Göğüs, bel, basen, boy, omuz, kol, ürün ve iç bacak ölçüleri yalnız ilgili siparişin hazırlanması ve müşteriye özel dikim için alınır. Standart beden bunların yerini almaz; sağlık bilgisi istenmez. Ölçüler reklam, müşteri profillemesi veya başka siparişler için kendiliğinden yeniden kullanılmaz. Kanuni delil saklama zorunluluğu varsa kullanım yalnız ilgili hakkın korunmasıyla sınırlanır.`,
  `İncelenen NRS uygulama kodu ölçü, adres veya sipariş ayrıntılarını Meta Pixel olaylarına eklemez; açık çağrılar yalnız PageView olaylarıdır, otomatik olay yapılandırması kapalıdır. Admin, checkout ve profil yollarında NRS'nin yeni PageView çağrısı yapılmaz. Bu, Meta'nın bağlantı/cihaz/sayfa bilgilerini hiç işlemediği anlamına gelmez; reklam betiği ayrı izinle çalışır. Ölçülerin teknik barındırma/veritabanı hizmetinde işlenmesi reklam servisine ölçü gönderilmesinden farklıdır.`,
  `Ölçülere üretim için gerekli yetkililer dışında erişim verilmemelidir; başka müşterilere açık paylaşım yapılmaz. Bu yasal yayın erişim yetkilerini değiştirmez ve otomatik ölçü/sipariş kaydını açmaz. Hazırlanmış müşteri/admin erişim kontrolleri kayıt sistemi açılmadan önce canlı ortamda doğrulanmalıdır; yerel kontrolün bulunması canlı güvenliğin tamamlandığı iddiası değildir. WhatsApp veya e-posta üzerinden kendiniz ölçü iletirseniz bunlar seçtiğiniz iletişim hizmetinde de işlenir; sağlık bilgisi veya gereksiz belge göndermeyin.`,
]
for (const document of Object.values(DOCUMENTS_V1_4)) {
  for (const section of document.sections) {
    section.paragraphs = section.paragraphs.map(text => {
      if (text.startsWith('Tüketicinin özel isteği')) return custom
      if (text.startsWith('Cayma bildiriminizden itibaren')) return 'Yasal cayma hakkı bulunan durumda bildiriminizden itibaren 14 gün içinde ürünü geri gönderin; NRS ürünü kendisi geri almayı teklif ederse gönderme yükümlülüğü uygulanmaz. ' + returns
      if (text.startsWith('Teslimat adresi, taahhüt edilen süre')) return DELIVERY_TERMS + ' Kargo firması henüz belirlenmemiştir; taşıyıcı ve varsa fiilen sunulabilen teslimat bilgileri belli olduğunda bildirilir. Anlaşmalı taşıyıcı veya takip hizmeti taahhüt edilmez. Gecikmede yasal fesih ve geri ödeme hakları korunur.'
      if (text.startsWith('Teslimatın doğru yapılabilmesi')) return 'Adres ve iletişim bilgilerinizi kontrol edin; değişiklikleri mümkün olan en kısa sürede bildirin. Kargo firması henüz belirlenmemiştir. Anlaşmalı taşıyıcı, takip numarası veya otomatik takip mesajı hizmeti taahhüt edilmez. Teslimat durumunu şirket iletişim e-postasından sorabilirsiniz.'
      if (text.startsWith('Beden veya model değişimi')) return `Özel dikim ürünlerde isteğe bağlı beden/model değişimi talebinizi ${email} adresine iletin; üretim olanağı ve varsa ayrıca kabul edeceğiniz koşullarla değerlendirilir. Gönüllü değişim, yasal cayma veya ayıplı mal haklarının yerine geçmez. Hatalı üretim ve yanlış gönderimde kanuni masraflar tüketiciye yüklenmez.`
      if (text.startsWith('Standart ürünlerde tüketici')) return 'Mevzuattaki cayma istisnasının uygulanmadığı ürünlerde tüketici, teslimden itibaren 14 gün içinde gerekçe göstermeden ve cezai şart ödemeden cayabilir. Teslimden önce de bildirim yapılabilir. Yazılı veya kalıcı veri saklayıcısı üzerinden süresinde bildirim yeterlidir; satıcının önceden onayını almak gerekmez.'
      return text.replace('Tercih kaydı bu tarayıcıda 180 gün saklanır.', 'Reklam tercihi bu tarayıcıda 180 gün geçerli kabul edilir. Süresi dolan tercih kod tarafından otomatik silinmez; yeniden tercih sorulur ve yeni seçim kaydı günceller. Tarayıcı depolamasını temizleyerek eski kaydı kaldırabilirsiniz.')
    })
  }
}
for (const slug of ['mesafeli-satis-sozlesmesi','on-bilgilendirme-formu','iade-ve-degisim','iptal-kosullari','kargo-ve-teslimat']) {
  DOCUMENTS_V1_4[slug].sections.push({ title: 'Taşıyıcı belirlenmeden yasal iade yöntemi', paragraphs: [DELIVERY_TERMS, custom, returns] })
}
const cancellation = DOCUMENTS_V1_4['iptal-kosullari'].sections
cancellation.find(s => s.title === 'İptal talebinin iletilmesi')!.paragraphs = [
  `İptal/değişim veya yasal cayma bildiriminizi ${email} adresine iletebilirsiniz; siparişi bulmaya yeterli bilgi verin. Kanunen geçerli diğer bildirim yöntemleri saklıdır. Mümkünse üretime başlanmadan bildirin; bu öneri yasal haklar için genel bir süre sınırı veya ret şartı değildir.`,
]
const ordinary = cancellation.find(s => s.title === 'Standart ürünler')!
ordinary.title = 'Cayma hakkı bulunan ürünler'
ordinary.paragraphs = ['Mevzuattaki istisnanın uygulanmadığı ürünlerde üretime veya taşımaya başlanması tek başına cayma hakkını kaldırmaz. Teslim öncesinde ve teslimden itibaren 14 gün içinde kanuni hakkınızı kullanabilirsiniz.']
cancellation.find(s => s.title === 'Özel üretim')!.paragraphs = [custom, 'Cayma istisnası kapsamındaki siparişte gönüllü iptal talebi üretim durumu gözetilerek değerlendirilir; koşullar tüketiciye bildirilmeden otomatik kesinti yapılmaz. Üretime başlanmış olması tek başına bütün yasal hakların reddine gerekçe değildir.']
for (const slug of ['kvkk','gizlilik-politikasi']) {
  const document = DOCUMENTS_V1_4[slug]
  document.sections = document.sections.filter(s => !['Saklama','Hizmet sağlayıcılar ve aktarım','Aktarım yapılabilecek taraflar/alıcı grupları','Siparişe bağlı beden ve ölçü bilgileri','Ödeme işlemleri'].includes(s.title))
  document.sections.push(
    { title: 'Özel dikim ölçüleri ve sınırlı kullanım', paragraphs: measurements },
    { title: 'Hizmet sağlayıcılar ve aktarımın mevcut durumu', paragraphs: providers },
    { title: 'Veri kategorilerine göre saklama ve silme planı', paragraphs: retention },
  )
}
